# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomFromText
                                 A QGIS plugin
 This plugin creates new cadastre parcels and beacons
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-28
        copyright            : (C) 2023 by Sivan Design Inc
        email                : guy.magen@sivandesign.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeomFromText class from file GeomFromText.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geom_from_text import GeomFromText
    return GeomFromText(iface)
